@echo off
mode 100
color b
echo ..........................::::::....................................................................
echo .............^!777???????????????????77!~^..........................................................
echo ...........:7JJJJJJJJJJJJJJJJJJJJJJJJJJJJJ!.........................................................
echo ...........!JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ^..~Y!.:J?...........7JJJJY~.....^J!.....................
echo ...........7JJJJJJJJJJJJ~^!7JJJJJJJJJJJJJJJ~..:PG:7B7.^^:..:^.:^~~5B?~~:.:^.~BJ:^:..:^^:............
echo ...........7JJJJJJJJJJJJ~...:^!?JJJJJJJJJJJ!...^GYPY:YPYP?.JG^~G7 YB~.5P:7G!^G5?P5:~PYYP!...........
echo ...........7JJJJJJJJJJJJ~.......^?JJJJJJJJJ!....?BG^^BJ.5G:JB^!B? YB!.5G:?B!^BJ.YB^JB77B5...........
echo ...........7JJJJJJJJJJJJ~...:^!?JJJJJJJJJJJ!....^GY.~B? 5G:?B^~B? YB!.5G:?B!^B? YG^YB?7?!...........
echo ...........7JJJJJJJJJJJJ~^!7JJJJJJJJJJJJJJJ~....^B5.^G5^PP.?B!?B? YB!.PG~YB!^BY^PG:?B7!G?...........
echo ...........~YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ^....:?7..~?J?^.^J?!?~.7J^.!J77J^:J77J7.:7JJ7:...........
echo ...........:7JJJJJJJJJJJJJJJJJJJJJJJJJJJJJ!.........................................................
echo .............^!77????????????????????77!~^..........................................................
echo ......................::::::........................................................................
pause >nul